Feature: Delete proof results from history


Scenario: Successfully delete a proof from the history (proof has to exist)

# First we have to add a proof the the history 
Given url 'http://localhost:9000/proof/testProject1/test.java/obligation/1/history'
And request 
"""
{
	"kind" : "success",
	"obligationIdx" : 0,
	"openGoals" : [],
	"resultMsg" : "Message generated by test",
	"targetName" : "DeleteTest"
}
"""
When method post
Then status 200
Then def historyId = response 

# Now we have to check that the saved proof is present in the history
Given url 'http://localhost:9000/proof/testProject1/test.java/obligation/1/history/'
And request {}
When method get
Then status 200
And match response contains Number(historyId)


# Now delete the added proof from the history
Given url 'http://localhost:9000/proof/testProject1/test.java/obligation/1/history/' + historyId
And request {}
When method delete
Then status 200


# Now check that the delete proof isn't present in the history anymore
Given url 'http://localhost:9000/proof/testProject1/test.java/obligation/1/history/'
And request {}
When method get
Then status 200
And match response !contains Number(historyId)


Scenario: Try to delete a proof from the history which doesn't exist (supposed to throw an error)

Given url 'http://localhost:9000/proof/testProjectWrong/testWrong.java/obligation/3/history/' + 66
And request {}
When method delete
Then status 404