Feature: List all proofIds which belong to a proof obligation


Scenario: List all proofIds which belong to a proof obligation

# First of, we have to save some proof to obligations

# Save proof1 to obligation 0
Given url 'http://localhost:9000/proof/testProject1/testListProofIds.java/obligation/0/history'
And request 
"""
{
	"kind" : "success",
	"obligationIdx" : 0,
	"openGoals" : [],
	"resultMsg" : "Message generated by test",
	"targetName" : "test1"
}
"""
When method post
Then status 200
Then def historyId1 = Number(response)


# Save proof2 to obligation 0
Given url 'http://localhost:9000/proof/testProject1/testListProofIds.java/obligation/0/history'
And request 
"""
{
	"kind" : "success",
	"obligationIdx" : 0,
	"openGoals" : [],
	"resultMsg" : "Message generated by test",
	"targetName" : "test1"
}
"""
When method post
Then status 200
Then def historyId2 = Number(response)

# Save proof3 to obligation 0
Given url 'http://localhost:9000/proof/testProject1/testListProofIds.java/obligation/0/history'
And request 
"""
{
	"kind" : "success",
	"obligationIdx" : 0,
	"openGoals" : [],
	"resultMsg" : "Message generated by test",
	"targetName" : "test1"
}
"""
When method post
Then status 200
Then def historyId3 = Number(response)
Then print 'got history id: ', historyId3

# Now check that the list of proofIds which belong to obligation 0 is correct

Given url 'http://localhost:9000/proof/testProject1/testListProofIds.java/obligation/0/history'
And request {}
When method get
Then status 200
And match response contains ['#(historyId1)', '#(historyId2)', '#(historyId3)']

