Feature: List all the obligation indices from the given file, which have a saved proof


Scenario: List all the obligation indices from the given file, which have a saved proof


# First of, we have to save some proof to obligations

# Save proof to obligation 0
Given url 'http://localhost:9000/proof/testProject1/testListObligations.java/obligation/0/history'
And request 
"""
{
	"kind" : "success",
	"obligationIdx" : 0,
	"openGoals" : [],
	"resultMsg" : "Message generated by test",
	"targetName" : "test1"
}
"""
When method post
Then status 200

# Save proof to obligation 1
Given url 'http://localhost:9000/proof/testProject1/testListObligations.java/obligation/1/history'
And request 
"""
{
	"kind" : "success",
	"obligationIdx" : 0,
	"openGoals" : [],
	"resultMsg" : "Message generated by test",
	"targetName" : "test1"
}
"""
When method post
Then status 200

# Save proof to obligation 2
Given url 'http://localhost:9000/proof/testProject1/testListObligations.java/obligation/2/history'
And request 
"""
{
	"kind" : "success",
	"obligationIdx" : 0,
	"openGoals" : [],
	"resultMsg" : "Message generated by test",
	"targetName" : "test1"
}
"""
When method post
Then status 200

# Now the actual test starts, check whether the listObligations endpoint shows all the 
# newly added proofs
Given url 'http://localhost:9000/proof/testProject1/testListObligations.java/obligation'
And request {}
When method get
Then match response contains [0, 1, 2]
