Feature: Save and retrieve the last proof


  #Scenario: Save the last proof
Scenario: Check whether the last proof (of the same obligation) is the one we just saved


Given url 'http://localhost:9000/proof/testProject1/SomeTest.java/obligation/1/last'
And request 
"""
{
	"kind" : "success",
	"obligationIdx" : 0,
	"openGoals" : [],
	"resultMsg" : "Message generated by test",
	"targetName" : "test1"
}
"""
When method post 
Then status 200 
Then def historyId = Number(response)



Given url 'http://localhost:9000/proof/testProject1/SomeTest.java/obligation/1/last'
And request {}
When method get
Then status 200 
And match response contains
"""
{
	"kind" : "success",
	"obligationIdx" : 0,
	"openGoals" : [],
	"resultMsg" : "Message generated by test",
	"targetName" : "test1"
}
"""


Scenario: Try to retrieve a proof which doesn't exist (supposed to throw error)


Given url 'http://localhost:9000/proof/testProject1/SomeTest.java/obligation/2/last'
And request {}
When method get
Then status 404
